---
name: print github ref
# yamllint disable-line rule:truthy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - master
      # Push events to branches matching refs/heads/releasev*.*
      - "release*"
    tags:
      - "v*"
jobs:
  push:
    name: Print ref
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        # github tag will be like refs/tags/v0.1.0 :10 removes the first 10 characters
        run: echo RELEASE_VERSION=$(echo ${GITHUB_REF:10}) >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - name: publish multi-arch image
        # podman cannot pull images with both tag and digest
        # https://github.com/containers/buildah/issues/1407
        # use docker to build images
        run: echo ${RELEASE_VERSION}
