---
name: print github ref
# yamllint disable-line rule:truthy
on: [push]
jobs:
  push:
    name: Print ref
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: set the env
        run: |
          echo "QUAY_IO_USERNAME=${{ secrets.QUAY_USERNAME }}" >> $GITHUB_ENV
          echo "GITHUBB_TOKEN=${{ secrets.QUAY_PASSWORD }}" >> $GITHUB_ENV
          echo "GITHUB_USER=${{ secrets.QUAY_USERNAME }}" >> $GITHUB_ENV
          echo "GITHUB_EMAIL=test.example.com" >> $GITHUB_ENV
      - name: Do login
        run: ./deploy.sh
