---
name: print github ref
# yamllint disable-line rule:truthy
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - master
      # Push events to branches matching refs/heads/releasev*.*
      - "release*"
    tags:
      - "v*"
jobs:
  push:
    name: Print ref
    runs-on: ubuntu-latest
    steps:
      - name: print github ref
        # github tag will be like refs/tags/v0.1.0 :10 removes the first 10 characters
        run: echo ${github.ref}
      - name: Set build environment to test otherwise
        if: ${{ !contains(github.ref, 'master') }}
        run: echo "BUILD_ENV=test"
