---
name: print github ref
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  push:
    name: Print ref
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check am i able to print the github token
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./deploy.sh
